name: CI

on:
  push:
    branches: master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - run: npm run build:storybook
      - uses: Reggionick/s3-deploy@v3.1.1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          folder: .storybook-dist
          bucket: vue-pb-www
          bucket-region: us-east-1
          dist-id: E14BL0PIUW6TO4
          invalidation: "*"
          delete-removed: true
          private: true
